#!/bin/sh

# --- enable verbosity for common commands ---


alias \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  bc="bc -ql" \
  mkd="mkdir -pv" \
  yt="yt-dlp --embed-metadata -i" \
  yta="yt -x -f bestaudio/best" \
  ffmpeg="ffmpeg -hide_banner"


# --- colorize commands when possible ---
alias \
  ls="ls -hN --color=auto --group-directories-first" \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi" \
  ip="ip -color=auto"


# --- command abbreviations ---
alias \
  cat="bat" \
  b="buku --suggest" \
  ka="killall" \
  g="git" \
  sdn="shutdown -h now" \
  e="nvim" \
  v="nvim" \
  vim="nvim" \
  c="clear" \
  t="exa --tree -L 2" \
  p="pacman"


# --- git commands ---

alias \
  gcot="git commit" \
  ga="git add" \
  gr="git rm -r --cached" \
  gall="git add " \
  gp="git push" \
  gc="git commit -m" \
  gam="git commit -mend" \
  gre="git remote add" \
  gst="git status" \
  glog="git log" \
  gcl="git clone"


# --- pacman commands ---

alias \
  pac="pacman -S" \
  pacu="pacman -Syu"\
  pacr="pacman -Rs" \
  pacs="pacman -Ss" \
  paci="pacman -Si" \
  paclo="pacman -Qdt" \
  pacc="pacman -Scc" \
  paclf="pacman -Ql"


# --- dot files ---

alias \
  dots="git --git-dir=$HOME/.cfg/ --work-tree=$HOME"
  gdcot="git --git-dir=$HOME/.cfg/  commit" \
  gda="git --git-dir=$HOME/.cfg/  add" \
  gdr="git --git-dir=$HOME/.cfg/  rm -r --cached" \
  gdall="git --git-dir=$HOME/.cfg/  add " \
  gdp="git --git-dir=$HOME/.cfg/  push" \
  gdc="git --git-dir=$HOME/.cfg/  commit -m" \
  gdam="git --git-dir=$HOME/.cfg/  commit --amend" \
  gdre="git --git-dir=$HOME/.cfg/  remote add" \
  gdst="git --git-dir=$HOME/.cfg/  status" \
  gdlog="git --git-dir=$HOME/.cfg/  log" \
  gdcl="git --git-dir=$HOME/.cfg/  clone"
#squash="git reset --soft HEAD~1 && git commit --edit -m"$(git log --format=%B --reverse HEAD..HEAD@{1})\""

# --- lazy git ---

alias \
    lg="lazygit" \
    lgd="lazygit --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"


# --- zk notebooks ---

alias \
    zkt="zk new --title" \
    zkl="zik list"



# --- tmux ---

alias \
  tmux='systemd-run --scope --user tmux' \
  ta='tmux attach-session -t' \
  tn='tmux new-session' \
  tr='tmux rename-session -t' \
  tl='tmux list-sessions'

# --- moving around quickly ---

alias \
  sd="cd ~ && cd \$(fd . -t d | fzf)" \
  cconf="cd ~ && cd \$(fd . '$XDG_CONFIG_HOME' -t d --hidden | fzf)" \
  econf="cd ~ && nvim \$(fd . '$XDG_CONFIG_HOME' -t f --hidden | fzf)" \
  ccode="cd ~ && cd \$(fd . '$HOME/src' -t d --hidden | fzf)" \
  ecode="cd ~ && nvim \$(fd . '$HOME/src' -t f --hidden | fzf)"
