#!/bin/sh

# --- substring search ---

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down


# --- vi mode ---

bindkey -v


# --- use vim keys in tab complete menu ---

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# --- edit line in vim with ctrl-e ---

bindkey '^e' edit-command-line
bindkey -M vicmd '^[[P' vi-delete-char
bindkey -M vicmd '^e' edit-command-line
bindkey -M visual '^[[P' vi-delete

