#!/bin/sh

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR_0="DP-1-1"
EXTERNAL_MONITOR_1="DP-1-2"
EXTERNAL_MONITOR_2="DP-2"

# check if monitors are connected

MON_0_CONN=$(xrandr -q | grep "${EXTERNAL_MONITOR_0} connected")
MON_1_CONN=$(xrandr -q | grep "${EXTERNAL_MONITOR_1} connected")
MON_2_CONN=$(xrandr -q | grep "${EXTERNAL_MONITOR_2} connected")

_run() {
	if ! pgrep -x "${1}" &>/dev/null; then
		"$@" &
	fi
}

monitor_double_mon_add() {
	# Move first 6 desktops to external monitors
    for ((desktop = 4; desktop < 7; desktop++)); do
		bspc desktop "$desktop" --to-monitor "$EXTERNAL_MONITOR_0"
	done

    for ((desktop = 7; desktop < 11; desktop++)); do
		bspc desktop "$desktop" --to-monitor "$EXTERNAL_MONITOR_1"
	done

	# Remove default desktop created by bspwm
	bspc desktop 0 --remove

	# reorder monitors
    bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR_0" "$EXTERNAL_MONITOR_1"
}

monitor_double_mon_remove() {
	# Add default temp desktop because a minimum of one desktop is required per monitor
    bspc monitor "$EXTERNAL_MONITOR_0" -a 0

	# Move all desktops except the last default desktop to internal monitor
	for desktop in $(bspc query -D -m "$EXTERNAL_MONITOR_0"); do
		bspc desktop "$desktop" --to-monitor "$INTERNAL_MONITOR"
	done

    # delete default desktops
	bspc desktop 0 --remove

	bspc monitor "$EXTERNAL_MONITOR_1" -a 0

    # Move all desktops except the last default desktop to internal monitor
	for desktop in $(bspc query -D -m "$EXTERNAL_MONITOR_1"); do
		bspc desktop "$desktop" --to-monitor "$INTERNAL_MONITOR"
	done

    # delete default desktops
	bspc desktop 0 --remove

	# reorder desktops
	bspc monitor "$INTERNAL_MONITOR" -o 1 2 3 4 5 6 7 8 9 10
}

monitor_single_mon_add() {
	# Move first 6 desktops to external monitors
    for ((desktop = 5; desktop < 11; desktop++)); do
		bspc desktop "$desktop" --to-monitor "$EXTERNAL_MONITOR_2"
	done

	# Remove default desktop created by bspwm
	bspc desktop 0 --remove

	# reorder monitors
    bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR_2"
}

monitor_single_mon_remove() {
	# Add default temp desktop because a minimum of one desktop is required per monitor
    bspc monitor "$EXTERNAL_MONITOR_2" -a 0

	# Move all desktops except the last default desktop to internal monitor
	for desktop in $(bspc query -D -m "$EXTERNAL_MONITOR_2"); do
		bspc desktop "$desktop" --to-monitor "$INTERNAL_MONITOR"
	done

    # delete default desktops
	bspc desktop 0 --remove

	# reorder desktops
	bspc monitor "$INTERNAL_MONITOR" -o 1 2 3 4 5 6 7 8 9 10
}

if [ "$MON_0_CONN" ] && [ "$MON_1_CONN" ]; then
    autorandr --load docked
	monitor_double_mon_add
else
	monitor_double_mon_remove
fi

# Background
_run hsetroot -cover ~/pix/wallpapers/misc/feet-on-the-dashboard.png

# Polybar
_run $XDG_CONFIG_HOME/polybar/launch.sh
